-- This script populates the "Users" and "Items" tables with sample data.
-- It assumes that the 'populate_universities.sql' script has already been run.

DO $$
    DECLARE
        uaic_id uuid;
        tuiasi_id uuid;
        unibuc_id uuid;
        user1_id uuid := gen_random_uuid();
        user2_id uuid := gen_random_uuid();
        user3_id uuid := gen_random_uuid();
        item1_id uuid := 'b7ee420d-6130-4678-8a94-7d2fe8178041';
        item2_id uuid := gen_random_uuid();
        item3_id uuid := gen_random_uuid();
        -- This is a placeholder hash for a simple password like 'Password123!'.
        -- In a real application, this hash would be generated by ASP.NET Core Identity.
        password_hash text := 'AQAAAAIAAYagAAAAE...'; -- Example hash, not a real one.

    BEGIN
        -- Fetch University IDs
        SELECT "Id" INTO uaic_id FROM "Universities" WHERE "ShortCode" = 'UAIC';
        SELECT "Id" INTO tuiasi_id FROM "Universities" WHERE "ShortCode" = 'TUIASI';
        SELECT "Id" INTO unibuc_id FROM "Universities" WHERE "ShortCode" = 'UB';

        -- Insert Users
        -- Note: SecurityStamp and ConcurrencyStamp are generated for simplicity.
        INSERT INTO "Users" (
            "Id", "FirstName", "LastName", "UniversityId", "CreatedAt",
            "UserName", "NormalizedUserName", "Email", "NormalizedEmail", "EmailConfirmed",
            "PasswordHash", "SecurityStamp", "ConcurrencyStamp", "PhoneNumberConfirmed", "TwoFactorEnabled", "LockoutEnabled", "AccessFailedCount"
        ) VALUES
              (
                  user1_id, 'Mihai', 'Popescu', uaic_id, NOW() AT TIME ZONE 'UTC',
                  'mihai.popescu', 'MIHAI.POPESCU', 'mihai.popescu@uaic.ro', 'MIHAI.POPESCU@UAIC.RO', true,
                  password_hash, gen_random_uuid()::text, gen_random_uuid()::text, false, false, true, 0
              ),
              (
                  user2_id, 'Elena', 'Ionescu', tuiasi_id, NOW() AT TIME ZONE 'UTC',
                  'elena.ionescu', 'ELENA.IONESCU', 'elena.ionescu@tuiasi.ro', 'ELENA.IONESCU@TUIASI.RO', true,
                  password_hash, gen_random_uuid()::text, gen_random_uuid()::text, false, false, true, 0
              ),
              (
                  user3_id, 'Andrei', 'Georgescu', unibuc_id, NOW() AT TIME ZONE 'UTC',
                  'andrei.georgescu', 'ANDREI.GEORGESCU', 'andrei.georgescu@unibuc.ro', 'ANDREI.GEORGESCU@UNIBUC.RO', true,
                  password_hash, gen_random_uuid()::text, gen_random_uuid()::text, false, false, true, 0
              );

        -- Insert Items
        INSERT INTO "Items" (
            "Id", "OwnerId", "Name", "Description", "Category", "Condition", "IsAvailable", "CreatedAt"
        ) VALUES
              (
                  item1_id, user1_id, 'Data Structures and Algorithms', 'A comprehensive book on algorithms, perfect for exam preparation.', 'Book', 'Good', true, NOW() AT TIME ZONE 'UTC'
              ),
              (
                  item2_id, user1_id, 'Scientific Calculator', 'Casio FX-991EX, used for one semester.', 'Electronics', 'Excellent', true, NOW() AT TIME ZONE 'UTC'
              ),
              (
                  item3_id, user2_id, 'Introduction to .NET', 'Course textbook for the .NET programming class.', 'Book', 'Fair', true, NOW() AT TIME ZONE 'UTC'
              );

    END $$;
